### ISSUE TITLE
.csv can't be shown in jupyter

### ISSUE THREAD

**Issue by TsuITOAR** [procyon-rs/showata#28]
This is an extremely helpful crate, but I encountered some issues.
I tried to view a csv file in jupyter with this crate, but it has no effects;
```
:dep mime = "0.3"
:dep showata = "0.3"
showata::show_file_in_jupyter(*my_file*,mime::CSV,true)
```
it just returns
```
Ok(())
```

**Comment by TsuITOAR** [comment]
oh, seems csv is not officially supported, I hope it will be.

**Comment by ThomAub** [comment]
Hello thank you for using the crate :) 

Yes we could add a specific formatting for `mimi::CSV` ! I think we didn't feel the need because we often use showata within jupyter-lab that comes with a default viewer for csv files. 

If nonetheless you want to dislpay it as raw text you can use `mime::TEXT_PLAIN` with a semicolon at the end to ensure you print the content and not the default return `Ok(())` from the function.

```rust
show_file_in_jupyter("res/sample_csv.csv", "text/plain", true);
```

Hope it can help :)  

<img width="1022" alt="jupyter-lab-csv-viewer" src="https://user-images.githubusercontent.com/26622992/142768162-f3f13874-6150-40eb-b1de-dc6ae8572a57.png">
<img width="1022" alt="display-as-plain-text" src="https://user-images.githubusercontent.com/26622992/142768167-19c7c0d9-1313-4370-a9c0-f56e1b5f8907.png">
